### ISSUE TITLE
Potentially unrecognized selector sent to paginator:didReceiveResults

### ISSUE THREAD

**Issue by eddelacruz** [nmondollot/NMPaginator#8]
//NMPaginator.m

//From:
 [self.delegate paginator:self didReceiveResults:results];

//To:
if ([self respondsToSelector:@selector(paginator:didReceiveResults:)]) {
    [self.delegate paginator:self didReceiveResults:results];
}

**Comment by nmondollot** [comment]
It's because this selector is required in the NMPaginatorDelegate : https://github.com/nmondollot/NMPaginator/blob/14a67005f72cc8d1be013490b31511a0945d09c5/NMPaginator/NMPaginator.h#L17

It doesn't make sense to not implement this delegate methods, that's why I don't check if the delegate responds to this selector
